export const SliderData = [
    {
        image:
        '/coping-gallery-image1.jpg',
    },
    {
        image:
        '/coping-gallery-image2.jpg',
    },
    {
        image:
        '/coping-gallery-image3.jpg',
    },
    {
        image:
        '/coping-gallery-image4.jpg',
    },
    {
        image:
        '/coping-gallery-image5.jpg',
    },
    {
        image:
        '/coping-gallery-image6.jpg',
    },
    {
        image:
        '/coping-gallery-image7.jpg',
    },
    {
        image:
        '/coping-gallery-image8.jpg',
    },
    {
        image:
        '/coping-gallery-image9.jpg',
    },
    {
        image:
        '/coping-gallery-image10.jpg',
    },
    {
        image:
        '/coping-gallery-image11.jpg',
    },
    {
        image:
        '/coping-gallery-image12.jpg',
    },
    {
        image:
        '/coping-gallery-image13.jpg',
    },
    {
        image:
        '/coping-gallery-image14.jpg',
    },
  ];