import Head from 'next/head';
import Page from '../components/Page';
import Newsletter from '../components/Newsletter';

export default function contact() {
  return (
    <div>
      <Head>
        <title>Pilates with Nat | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div> 
      <Page 
      heading='Join Our Community' 
      heading2="Scroll down to subscribe for class info" 
      para="I want you to feel comfortable and welcome, so it's great if I can get to know you a bit before you join a class. I won't send you loads of emails, just information about classes - Thanks, hopefully speak to you soon!" />   
      </div>
      <Newsletter />
    
    </div>
    
  );
}