import Head from 'next/head';
import Page from '../components/Page';
import { Contact } from '../components/Contact';

export default function contact() {
  return (
    <div>
      <Head>
        <title>Pilates with Nat | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div> 
      <Page 
      heading='Join Our Community' 
      heading2="I want you to feel comfortable and welcome." 
      para="It's great if I can get to know you a bit before you join a class. That way I can have you in my thoughts as I create my class plans. Please subscribe to my mailing list below and I'll get back to you. I won't send you loads of emails, just information about classes - Thanks, hopefully speak to you soon!" />   
      </div>
      <Contact />
    
    </div>
    
  );
}