import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coping UK | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Stories For a Brighter Future' message='Our goal is to create an ongoing movement towards a more caring & conscious society. With your help we can build on our strong foundations & share stories that inspire positive change.' button='Saturday 17th June Event'/>
      <Slider slides={SliderData} />
    </div>
  );
}
